config/routes.rb
BiddingFeeAuction::Application.routes.draw do
  
  resources :listings
  
  resources :auctions do
    collection do
      post 'bid'
    end
  end
  get 'search' => 'auctions#search'
  post 'auctions/view_as/:type' => 'auctions#view_as'
  
  resources :users do
    collection do
      post 'login'
      post 'logout'
    end
  end
  
  post 'pusher/auth'
  
  root :to => 'home#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  attr_accessible :user_id, :end_time, :id, :price, :listing_id
  belongs_to :listing
  belongs_to :user
  
  validates :price, :listing_id, :presence => true
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  include ActionView::Helpers::NumberHelper # include number functions
  
  before_filter :get_auction, :only => [:destory, :update, :bid, :edit, :show]
  
  # GET /auctions
  def index
    @auctions = Auction.find(:all, :conditions => "end_time >= "+Time.new.to_i.to_s)    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @auctions }
      format.xml { render xml: @auctions }
    end
  end

  # GET /auctions/1
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @auction }
    end
  end

  # GET /auctions/new
  def new
    if 1 == 2 # auth for admin
      render_404
    else
      @auction = Auction.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @auction }
      end
    end
  end

  # GET /auctions/1/edit
  def edit
  end

  # POST /auctions
  def create
    @auction = Auction.new(params[:auction])
    @auction.end_time = Time.new.to_i + 1.day

    respond_to do |format|
      if @auction.save
        format.html { redirect_to @auction, notice: 'Auction was successfully created.' }
        format.json { render json: @auction, status: :created, location: @auction }
      else
        format.html { render action: "new" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /auctions/1
  def update

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to @auction, notice: 'Auction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  def destroy
    @auction.destroy

    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end
  
  # POST /auctions/bid
  def bid
    app = Rails.application.routes.url_helpers # routes
    helper = ApplicationController.helpers # include helpers
    
    @user = User.find(@current_user.id)
    
    if @user.bids > 0
      @user.bids -= 1;
      @user.save()
      
      @auction.price += 1
      @auction.user_id = @user.id
      @auction.save()
      
      render :json => { 
        :id => @auction.id,
        :price => (number_to_currency @auction.price*0.01),
        
        :username => (helper.link_to @user.username, app.user_path(@user.id)),
        :bids => (number_with_delimiter @user.bids)
      }
    else
      render :json => { :error => 'bids' }
    end
  end
  
  def search
    if !params[:q].nil?
      @auctions = 
        Auction
          .joins(:listing)
          .where("listings.name LIKE :query AND auctions.end_time >= :time", 
            :query => "%"+params[:q]+"%",
            :time => Time.new.to_i.to_s
          )
    end
    
    render :file => "auctions/index", :locals => { :auctions => @auctions }
  end
  
  # POST /auctions/view_as/list
  def view_as
    session[:view_as] = params[:type]
    render :nothing => true
  end
  
  # DRY Functions
  def get_auction
  	@auction = Auction.find(params[:id])
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper
end

app/views/auctions/_auction.html.erb
<div class="auction <%= session[:view_as] %>" data-id="<%= auction.id %>">
  <%= link_to auction.listing.name, auction, :class => "item_name" %>
  <%= link_to image_tag(auction.listing.image_url, :alt => auction.listing.name), auction %>
  <div class="retail"><%= number_to_currency auction.listing.retail, :precision => 0 %> <span>retail</span></div>
  <div class="end_time" data-end-time="<%= auction.end_time %>">00:00:00</div>
  <div class="price"><%= number_to_currency auction.price*0.01 %></div>
  <div class="highest_bidder"><%= link_to auction.user.username, auction.user %></div>
  <div class="bid_container"><input type="button" class="button_bid" value="Bid"></div>
</div>

app/views/auctions/_bidwindow.html.erb
<% view_as = session[:view_as] || "window" %>
<div class="auction <%= view_as %>" data-id="<%= auction.id %>">
  <%= link_to auction.listing.name, auction, :class => "item_name" %>
  <%= link_to image_tag(auction.listing.image_url, :alt => auction.listing.name), auction %>
	<div class="retail"><%= number_to_currency auction.listing.retail, :precision => 0 %> retail</div>
	<div class="end_time" data-end-time="<%= auction.end_time %>">00:00:00</div>
	<div class="price"><%= number_to_currency auction.price*0.01 %></div>
	<div class="highest_bidder"><%= auction.user.username %></div>
	<input type="button" class="button_bid" value="Bid">
</div>

app/views/auctions/_form.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :listing_id %><br />
    <%= f.text_field :listing_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auctions/edit.html.erb
<h1>Editing auction</h1>

<%= render 'form' %>

<%= link_to 'Show', @auction %> |
<%= link_to 'Back', auctions_path %>

app/views/auctions/index.html.erb
<section class="filter-bar">
  <section class="filters">
    <a class="gridded" href="#"></a>
    <a class="listed" href="#"></a>
    <%= form_tag "/search", :method => "get", :id => "search" do %>
      <%= text_field_tag :q, params[:q], :placeholder => "Search auctions" %>
      <%= submit_tag "Search", :name => "" %>
    <% end %>
  </section>
</section>

<h1 class="page-header">Browse listings</h1>

<div class="<%= session[:view_as] %> auction title-bar">
  <div class="item_name">Item name</div>
  <div class="retail">Retail price</div>
  <div class="end_time">End time</div>
  <div class="price">Price</div>
  <div class="highest_bidder">Bidder</div>
  <div class="bid_container"></div>
</div>

<% if !@auctions.nil? && @auctions.count > 0 %>
  <% @auctions.each do |auction| %>
    <%= 
    render :partial => 'auction', :locals => { 
      :auction => auction
    } 
    %>
  <% end %>
<% elsif controller.action_name == "search" %>
  <%= "Search didn't return any results" %>
<% else %>
  <%= "No auctions currently running" %>
<% end %>

app/views/auctions/new.html.erb
<h1>New auction</h1>

<%= render 'form' %>

<%= link_to 'Back', auctions_path %>

app/views/auctions/show.html.erb
<!--<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @auction.id %>
</p>

<p>
  <b>Name:</b>
  <%= @auction.listing.name %>
</p>

<p>
  <b>Price:</b>
  <%= @auction.price %>
</p>

<p>
  <b>Bidder:</b>
  <%= @auction.user.username %>
</p>

<p>
  <b>End time:</b>
  <%= @auction.end_time %>
</p>

<%= link_to 'Edit', edit_auction_path(@auction) %> |
<%= link_to 'Back', auctions_path %>-->

<div class="auction single-item">
  <section class="info">
    <div class="item_name">Generated name</div>
    <div class="retail"><%= number_to_currency @auction.listing.retail, :precision => 0 %> <span>retail</span></div>
    <p class="item_description">
      The new third-generation iPad features a stunning Retina display, 5MP iSight camera, and ultrafast 4G LTE.
      <a href="#">Learn more</a>
    </p>
  </section>
  
  <section class="images">
    <img alt="ipad" src="/assets/listings/ipad-large.png">
    <a href="#">View more images</a>
  </section>
  
  <section class="actions" data-id="<%= @auction.id %>">
    <div class="price_container">
      Auction price
      <span class="price"><%= number_to_currency (@auction.price*0.01) %>
    </div>
    <div class="end_time_container">
      Time left
      <span class="end_time" data-end-time="<%= @auction.end_time %>">00:00:00</span>
    </div>
    <div class="highest_bidder_container">
      Highest bidder
      <span class="highest_bidder"><%= link_to @auction.user.username, @auction.user %></span>
    </div>
    <div class="bid_container"><input type="button" class="button_bid" value="Bid"></div>
    <p class="fine_print">Fine printed stuff could go here or something. Blarg blarg blarg blarg</p>
  </section>
</div>