config/routes.rb
BiddingFeeAuction::Application.routes.draw do
  
  resources :listings
  
  resources :auctions do
    collection do
      post 'bid'
    end
  end
  get 'search' => 'auctions#search'
  post 'auctions/view_as/:type' => 'auctions#view_as'
  
  resources :users do
    collection do
      post 'login'
      post 'logout'
    end
  end
  
  post 'pusher/auth'
  
  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  Stylus.debug = true # Show line numbers in compiled CSS
  
  protect_from_forgery
  
  # Check for keys initializer
  before_filter :check_keys_initializer
  
  def check_keys_initializer
    if !File.exist? "config/initializers/keys.rb"
      render :text => "Error. Missing /config/initializers/keys.rb"
    end
  end
  
  
  # Fetch current user
  before_filter :fetch_current_user
  
  def fetch_current_user
    return unless session[:user_id]
    @current_user = User.find(session[:user_id])
  end
  def logged_in?
    !@current_user.nil?
  end
  helper_method :logged_in?
  
  
  # Login required
  before_filter :authenticate, :only => [:bid]
  
  def authenticate
    if !logged_in?
      render :nothing => true, :status => 403
    end
  end
  
  
  # Generic 404 page
  def render_404
    render 'public/404.html', :status => 404, :layout => false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_login_form.html.erb
<% if !logged_in? %>
  <%= form_tag login_users_path do %>
    <%= 
    text_field_tag :username, (flash[:username] if flash[:username]), 
      :placeholder => "Username", 
      :class => ("error" if flash[:error] && flash[:error][:field] == "username") 
    %><%=
    password_field_tag :password, "", 
      :placeholder => "Password", 
      :class => ("error" if flash[:error] && flash[:error][:field] == "password")
    %>
    <a href="#">Forgot password?</a>
    <%= submit_tag "Log in" %>
  <% end %>
<% else %>
  <%= form_tag logout_users_path do %>
    <div><%= @current_user.username %></div>
    <div class="user-bids"><%= number_with_delimiter @current_user.bids %> bids</div>
    <%= submit_tag "Log out" %>
  <% end %>
<% end %>